### ISSUE TITLE
Procedure Tracker: Deviations

### ISSUE THREAD

**Issue by nvennin** [simplepharma/qms#12]
Following up on issue #1 

Tracker for creation of GDP procedure XCEUG Deviations

- [x] Issue created
- [x] Number assigned: 
- [x] Filename assigned
- [x] Branch created
- [x] Blank canvas created
- [x] Readme file updated
- [x] Author assigned
- [x] Pull request made

**Comment by nvennin** [comment]
Pull request #13
