### ISSUE TITLE
Procedure Tracker: Change control

### ISSUE THREAD

**Issue by nvennin** [simplepharma/qms#15]
Following up on issue #1 

Tracker for creation of GDP procedure 

- [x] Issue created
- [x] Number assigned: 
- [x] Filename assigned
- [ ] Branch created
- [ ] Blank canvas created
- [ ] Readme file updated
- [ ] Author assigned
- [ ] Pull request made

**Comment by nvennin** [comment]
Reviewed in proc-multiple branch. To be pulled into main with a bunch of document change requests.
