### ISSUE TITLE
Procedure tracker: Serialisation

### ISSUE THREAD

**Issue by nvennin** [simplepharma/qms#16]
Tracker for creation of GDP procedure

- [x] Issue created
- [x] Number assigned: AGDXV
- [ ] Filename assigned
- [ ] Branch created
- [ ] Blank canvas created
- [ ] Readme file updated
- [ ] Author assigned
- [ ] Pull request made

**Comment by nvennin** [comment]
Change spelling with an s

**Comment by nvennin** [comment]
@cescolier seems to be missing in the proc-multiple branch. Can you check? Please create a dedicated branch if that's the case. Thanks

**Comment by cescolier** [comment]
Hello Nicolas,

Indeed, SERIALIZATION has been forgotten. I add it in a dedicated branch.

Regards,
Caroline

*Caroline ESCOLIER*
*CASSIOPEE Solucions*
Av. del PESSEBRE 27, 4B
AD700 ESCALDES ENGORDANY - ANDORRA
@ : cassiopeesolucions@gmail.com
Tel : (376) 349.250

**Comment by cescolier** [comment]
Nicolas,

in this document, SERIALISATION, are mentioned TraceLink and
TraceLinkSystem.
I let them but I don't know if you use this tool or if it's specific Thx
and if it's better to erase it.

Caroline.

*Caroline ESCOLIER*
*CASSIOPEE Solucions*
Av. del PESSEBRE 27, 4B
AD700 ESCALDES ENGORDANY - ANDORRA
@ : cassiopeesolucions@gmail.com
Tel : (376) 349.250
