### ISSUE TITLE
Procedure Tracker: Artwork and Labelling

### ISSUE THREAD

**Issue by nvennin** [simplepharma/qms#17]
Tracker for creation of GDP procedure

- [x] Issue created
- [x] Number assigned:
- [ ] Filename assigned
- [ ] Branch created
- [ ] Blank canvas created
- [ ] Readme file updated
- [ ] Author assigned
- [ ] Pull request made

**Comment by nvennin** [comment]
Reviewed procedure and created template issue.
