### ISSUE TITLE
Procedure Tracker: Management review and monitoring

### ISSUE THREAD

**Issue by nvennin** [simplepharma/qms#18]
Following up on issue #1

Tracker for creation of GDP procedure

- [x] Issue created
- [x] Number assigned: **OZCFN**
- [x] Filename assigned
- [ ] Branch created
- [ ] Blank canvas created
- [ ] Readme file updated
- [ ] Author assigned
- [ ] Pull request made

**Comment by nvennin** [comment]
Reviewed text, to be submitted for approval in the next pull request.
