### ISSUE TITLE
Procedure Tracker: Quality Risk Management

### ISSUE THREAD

**Issue by nvennin** [simplepharma/qms#19]
Following up on issue #1

Tracker for creation of GDP procedure

- [x] Issue created
- [x] Number assigned: **LBHIY**
- [x] Filename assigned
- [ ] Branch created
- [ ] Blank canvas created
- [ ] Readme file updated
- [ ] Author assigned
- [ ] Pull request made

**Comment by nvennin** [comment]
reviewed, will be included in the next pull request.
