### ISSUE TITLE
Procedure Tracker: Receipt of medicinal products

### ISSUE THREAD

**Issue by nvennin** [simplepharma/qms#21]
Following up on issue #1

Tracker for creation of GDP procedure

- [x] Issue created
- [x] Number assigned: **VQICE**
- [x] Filename assigned
- [ ] Branch created
- [ ] Blank canvas created
- [ ] Readme file updated
- [ ] Author assigned
- [ ] Pull request made

**Comment by nvennin** [comment]
Reviewed, will be included in the next pull request.
