### ISSUE TITLE
Procedure Tracker: Recall procedure

### ISSUE THREAD

**Issue by nvennin** [simplepharma/qms#24]
Following up on issue #1

Tracker for creation of GDP procedure

- [x] Issue created
- [x] Number assigned: **VOZWP**
- [x] Filename assigned
- [ ] Branch created
- [ ] Blank canvas created
- [ ] Readme file updated
- [ ] Author assigned
- [ ] Pull request made

**Comment by nvennin** [comment]
@cescolier this proedure seems to be missing, isn't it?

**Comment by cescolier** [comment]
Hi,
strange, I am sure that it was here...I have a look



*Caroline ESCOLIER*
*CASSIOPEE Solucions*
Av. del PESSEBRE 27, 4B
AD700 ESCALDES ENGORDANY - ANDORRA
@ : cassiopeesolucions@gmail.com
Tel : (376) 349.250

**Comment by cescolier** [comment]
Hi Nicolas,

I made it in a new branch : https://github.com/simplepharma/qms/blob/recall_proc/procedures/Procedure_GDP_VOZWP_Recall_procedure.md
