### ISSUE TITLE
Procedure Tracker: Outsourced activities

### ISSUE THREAD

**Issue by nvennin** [simplepharma/qms#25]
Following up on issue #1

Tracker for creation of GDP procedure

- [x] Issue created
- [x] Number assigned: **HBQIN**
- [x] Filename assigned
- [ ] Branch created
- [ ] Blank canvas created
- [x] Readme file updated
- [ ] Author assigned
- [x] Pull request made

**Comment by nvennin** [comment]
Reviewd procedure. One todo:
- [ ] Open change request for qualification of Movianto
