### ISSUE TITLE
Procedure Tracker: Self-inspections

### ISSUE THREAD

**Issue by nvennin** [simplepharma/qms#26]
Following up on issue #1

Tracker for creation of GDP procedure

- [x] Issue created
- [x] Number assigned: **GMQHI**
- [x] Filename assigned
- [ ] Branch created
- [ ] Blank canvas created
- [ ] Readme file updated
- [ ] Author assigned
- [ ] Pull request made

**Comment by nvennin** [comment]
Reviewed procedure. One remaining action:
- [ ] Create self-inspection tracker
