### ISSUE TITLE
Procedure Tracker: Medicinal Product Returns

### ISSUE THREAD

**Issue by nvennin** [simplepharma/qms#28]
Following up on issue #1

Tracker for creation of GDP procedure

- [x] Issue created
- [x] Number assigned: **BMAXZ**
- [x] Filename assigned
- [ ] Branch created
- [ ] Blank canvas created
- [ ] Readme file updated
- [ ] Author assigned
- [ ] Pull request made

**Comment by nvennin** [comment]
Reviewed, will be included in the next proc-multiple branch update.
