### ISSUE TITLE
Procedure Tracker: CAPA

### ISSUE THREAD

**Issue by nvennin** [simplepharma/qms#29]
Following up on issue #1

Tracker for creation of GDP procedure

- [x] Issue created
- [x] Number assigned: **YUISV**
- [x] Filename assigned
- [ ] Branch created
- [ ] Blank canvas created
- [ ] Readme file updated
- [ ] Author assigned
- [ ] Pull request made

**Comment by nvennin** [comment]
Todo: create a CAPA template issue.
