### ISSUE TITLE
Procedure Tracker: Reporting of Adverse Events

### ISSUE THREAD

**Issue by nvennin** [simplepharma/qms#30]
Following up on issue #1

Tracker for creation of GDP procedure

- [x] Issue created
- [x] Number assigned: **GGNHM**
- [x] Filename assigned
- [ ] Branch created
- [ ] Blank canvas created
- [ ] Readme file updated
- [x] Author assigned
- [ ] Pull request made

**Comment by nvennin** [comment]
Reviewd the procedure in proc-multiple. Changes to be included in the next pull-request.
