### ISSUE TITLE
Document Tracker: Glossary

### ISSUE THREAD

**Issue by nvennin** [simplepharma/qms#31]
Following up on issue #1

Tracker for creation of quality controlled document

- [x] Issue created
- [x] Number assigned: ****
- [x] Filename assigned
- [ ] Branch created
- [ ] Blank canvas created
- [ ] Readme file updated
- [ ] Author assigned
- [ ] Pull request made
