### ISSUE TITLE
Procedure Tracker: Responsible Person

### ISSUE THREAD

**Issue by nvennin** [simplepharma/qms#8]
Following up on issue #1 

Tracker for creastion of GDP procedure XIDEX Responsible Person

- [x] Issue created
- [x] Number assigned: **XIDEX**
- [ ] Filename assigned // not yet, need to include _GDP_ in name
- [ ] Readme file // need to update to new filename

**Comment by nvennin** [comment]
- [ ] Need to update filename in git repos to include GDP

**Comment by nvennin** [comment]
Pull request submitted #11
