### ISSUE TITLE
Procedure Tracker: Documentation Control

### ISSUE THREAD

**Issue by nvennin** [simplepharma/qms#9]
Following up on issue #1 

Tracker for creastion of GDP procedure BWRPX Documentation Control

- [x] Issue created
- [x] Number assigned: **BWRPX**
- [x] Filename assigned
- [x] Branch created
- [x] Blank canvas created
- [ ] Readme file updated
- [x] Author assigned
- [ ] Pull request made

**Comment by nvennin** [comment]
Filename: procedures/Procedure_GDP_BWRPX_Documentation_Control.md

**Comment by nvennin** [comment]
Reviewed the text. To include in next update.
